<a href="https://colab.research.google.com/github/Geolist/first-repository/blob/main/%EC%B6%94%EC%B2%9C%EC%8B%9C%EC%8A%A4%ED%85%9C2_%EC%95%84%EC%9D%B4%EC%9C%A0%ED%8C%AC%EC%9D%B4_%EC%A2%8B%EC%95%84%ED%95%A0_%EB%A7%8C%ED%95%9C_%EB%8B%A4%EB%A5%B8_%EC%95%84%ED%8B%B0%EC%8A%A4%ED%8A%B8_%EC%B0%BE%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 데이터 용량이 너무 크니까 드라이브에 넣어놓고 진행

한번 세션 초기화 될때마다 눈물남

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
## 제 data 경로입니다 각자 경로에 맞게 고쳐봅시다

#  /content/drive/MyDrive/Colab Notebooks/데싸4기/추천시스템/data

In [3]:
import pandas as pd
import os


## 각자 경로에 맞게 고치기
#fname = os.getenv('HOME') + '/aiffel/recommendata_iu/data/lastfm-dataset-360K/usersha1-artmbid-artname-plays.tsv'

fname = '/content/drive/MyDrive/usersha1-artmbid-artname-plays.tsv'
col_names = ['user_id', 'artist_MBID', 'artist', 'play']   # 임의로 지정한 컬럼명
data = pd.read_csv(fname, sep='\t', names= col_names)      # sep='\t'로 주어야 tsv를 열 수 있습니다.
data.head(10)
data

user_id  \
0         00000c289a1829a808ac09c00daf10bc3c4e223b   
1         00000c289a1829a808ac09c00daf10bc3c4e223b   
2         00000c289a1829a808ac09c00daf10bc3c4e223b   
3         00000c289a1829a808ac09c00daf10bc3c4e223b   
4         00000c289a1829a808ac09c00daf10bc3c4e223b   
...                                            ...   
17535650                              sep 20, 2008   
17535651                              sep 20, 2008   
17535652                              sep 20, 2008   
17535653                              sep 20, 2008   
17535654                              sep 20, 2008   

                                   artist_MBID                artist  play  
0         3bd73256-3905-4f3a-97e2-8b341527f805       betty blowtorch  2137  
1         f2fb0ff0-5679-42ec-a55c-15109ce6e320             die Ärzte  1099  
2         b3ae82c2-e60b-4551-a76d-6620f1b456aa     melissa etheridge   897  
3         3d6bbeb7-f90e-4d10-b440-e153c0d10b53             elvenking   717  
4         bbd2ffd7-17f4-4506-8572-c1ea58c3f9a8  juliette & the licks   706  
...                                        ...                   ...   ...  
17535650  7ffd711a-b34d-4739-8aab-25e045c246da            turbostaat    12  
17535651  9201190d-409f-426b-9339-9bd7492443e2         cuba missouri    11  
17535652  e7cf7ff9-ed2f-4315-aca8-bcbd3b2bfa71       little man tate    11  
17535653  f6f2326f-6b25-4170-b89d-e235b25508e8             sigur rós    10  
17535654  40f5d9e4-2de7-4f2d-ad41-e31a9a9fea27            the smiths    10  

[17535655 rows x 4 columns]

In [4]:
# 사용하는 컬럼만 남겨줍니다.
using_cols = ['user_id', 'artist', 'play']
data = data[using_cols]
data.head(10)

user_id                   artist  play
0  00000c289a1829a808ac09c00daf10bc3c4e223b          betty blowtorch  2137
1  00000c289a1829a808ac09c00daf10bc3c4e223b                die Ärzte  1099
2  00000c289a1829a808ac09c00daf10bc3c4e223b        melissa etheridge   897
3  00000c289a1829a808ac09c00daf10bc3c4e223b                elvenking   717
4  00000c289a1829a808ac09c00daf10bc3c4e223b     juliette & the licks   706
5  00000c289a1829a808ac09c00daf10bc3c4e223b    red hot chili peppers   691
6  00000c289a1829a808ac09c00daf10bc3c4e223b                   magica   545
7  00000c289a1829a808ac09c00daf10bc3c4e223b  the black dahlia murder   507
8  00000c289a1829a808ac09c00daf10bc3c4e223b              the murmurs   424
9  00000c289a1829a808ac09c00daf10bc3c4e223b               lunachicks   403

In [5]:
data['artist'] = data['artist'].str.lower() # 검색을 쉽게 하기 위해 아티스트 문자열을 소문자로 바꿔줍시다.
data.head(10)

/tmp/ipython-input-5-3194040051.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['artist'] = data['artist'].str.lower() # 검색을 쉽게 하기 위해 아티스트 문자열을 소문자로 바꿔줍시다.


user_id                   artist  play
0  00000c289a1829a808ac09c00daf10bc3c4e223b          betty blowtorch  2137
1  00000c289a1829a808ac09c00daf10bc3c4e223b                die ärzte  1099
2  00000c289a1829a808ac09c00daf10bc3c4e223b        melissa etheridge   897
3  00000c289a1829a808ac09c00daf10bc3c4e223b                elvenking   717
4  00000c289a1829a808ac09c00daf10bc3c4e223b     juliette & the licks   706
5  00000c289a1829a808ac09c00daf10bc3c4e223b    red hot chili peppers   691
6  00000c289a1829a808ac09c00daf10bc3c4e223b                   magica   545
7  00000c289a1829a808ac09c00daf10bc3c4e223b  the black dahlia murder   507
8  00000c289a1829a808ac09c00daf10bc3c4e223b              the murmurs   424
9  00000c289a1829a808ac09c00daf10bc3c4e223b               lunachicks   403

In [6]:
condition = (data['user_id']== data.loc[0, 'user_id'])
data.loc[condition]

user_id                   artist  play
0   00000c289a1829a808ac09c00daf10bc3c4e223b          betty blowtorch  2137
1   00000c289a1829a808ac09c00daf10bc3c4e223b                die ärzte  1099
2   00000c289a1829a808ac09c00daf10bc3c4e223b        melissa etheridge   897
3   00000c289a1829a808ac09c00daf10bc3c4e223b                elvenking   717
4   00000c289a1829a808ac09c00daf10bc3c4e223b     juliette & the licks   706
5   00000c289a1829a808ac09c00daf10bc3c4e223b    red hot chili peppers   691
6   00000c289a1829a808ac09c00daf10bc3c4e223b                   magica   545
7   00000c289a1829a808ac09c00daf10bc3c4e223b  the black dahlia murder   507
8   00000c289a1829a808ac09c00daf10bc3c4e223b              the murmurs   424
9   00000c289a1829a808ac09c00daf10bc3c4e223b               lunachicks   403
10  00000c289a1829a808ac09c00daf10bc3c4e223b         walls of jericho   393
11  00000c289a1829a808ac09c00daf10bc3c4e223b           letzte instanz   387
12  00000c289a1829a808ac09c00daf10bc3c4e223b                goldfrapp   361
13  00000c289a1829a808ac09c00daf10bc3c4e223b               horrorpops   358
14  00000c289a1829a808ac09c00daf10bc3c4e223b             the butchies   329
15  00000c289a1829a808ac09c00daf10bc3c4e223b            jack off jill   316
16  00000c289a1829a808ac09c00daf10bc3c4e223b         babes in toyland   310
17  00000c289a1829a808ac09c00daf10bc3c4e223b         dropkick murphys   302
18  00000c289a1829a808ac09c00daf10bc3c4e223b            all:my:faults   288
19  00000c289a1829a808ac09c00daf10bc3c4e223b                 le tigre   281
20  00000c289a1829a808ac09c00daf10bc3c4e223b               schandmaul   244
21  00000c289a1829a808ac09c00daf10bc3c4e223b                    edguy   232
22  00000c289a1829a808ac09c00daf10bc3c4e223b      maximum the hormone   231
23  00000c289a1829a808ac09c00daf10bc3c4e223b                 all ends   229
24  00000c289a1829a808ac09c00daf10bc3c4e223b             jack johnson   227
25  00000c289a1829a808ac09c00daf10bc3c4e223b                eluveitie   222
26  00000c289a1829a808ac09c00daf10bc3c4e223b                rasputina   220
27  00000c289a1829a808ac09c00daf10bc3c4e223b    london after midnight   210
28  00000c289a1829a808ac09c00daf10bc3c4e223b              the killers   208
29  00000c289a1829a808ac09c00daf10bc3c4e223b                  mutyumu   205
30  00000c289a1829a808ac09c00daf10bc3c4e223b             judas priest   198
31  00000c289a1829a808ac09c00daf10bc3c4e223b               rob zombie   198
32  00000c289a1829a808ac09c00daf10bc3c4e223b             the bosshoss   189
33  00000c289a1829a808ac09c00daf10bc3c4e223b         blue öyster cult   185
34  00000c289a1829a808ac09c00daf10bc3c4e223b             sandra nasic   183
35  00000c289a1829a808ac09c00daf10bc3c4e223b               john mayer   182
36  00000c289a1829a808ac09c00daf10bc3c4e223b           sleater-kinney   175
37  00000c289a1829a808ac09c00daf10bc3c4e223b                  the who   168
38  00000c289a1829a808ac09c00daf10bc3c4e223b                 disciple   154
39  00000c289a1829a808ac09c00daf10bc3c4e223b                  tanzwut   153
40  00000c289a1829a808ac09c00daf10bc3c4e223b               guano apes   151
41  00000c289a1829a808ac09c00daf10bc3c4e223b       the rolling stones   150
42  00000c289a1829a808ac09c00daf10bc3c4e223b          little big town   145
43  00000c289a1829a808ac09c00daf10bc3c4e223b              team dresch   137
44  00000c289a1829a808ac09c00daf10bc3c4e223b                    betty   135
45  00000c289a1829a808ac09c00daf10bc3c4e223b                       l7   135
46  00000c289a1829a808ac09c00daf10bc3c4e223b                bif naked   134
47  00000c289a1829a808ac09c00daf10bc3c4e223b               girlschool   134
48  00000c289a1829a808ac09c00daf10bc3c4e223b          the wallflowers   131

In [7]:
# 유저 수
data['user_id'].nunique()

358868

In [8]:
# 아티스트 수
data['artist'].nunique()

291346

In [9]:
# 인기 많은 아티스트
artist_count = data.groupby('artist')['user_id'].count()
artist_count.sort_values(ascending=False).head(30)

artist
radiohead                77254
the beatles              76245
coldplay                 66658
red hot chili peppers    48924
muse                     46954
metallica                45233
pink floyd               44443
the killers              41229
linkin park              39773
nirvana                  39479
system of a down         37267
queen                    34174
u2                       33206
daft punk                33001
the cure                 32624
led zeppelin             32295
placebo                  32072
depeche mode             31916
david bowie              31862
bob dylan                31799
death cab for cutie      31482
arctic monkeys           30348
foo fighters             30144
air                      29795
the rolling stones       29754
nine inch nails          28946
sigur rós                28901
green day                28732
massive attack           28691
moby                     28232
Name: user_id, dtype: int64

In [10]:
# 유저별 몇 명의 아티스트를 듣고 있는지에 대한 통계
user_count = data.groupby('user_id')['artist'].count()
user_count.describe()

count    358868.000000
mean         48.863234
std           8.524272
min           1.000000
25%          46.000000
50%          49.000000
75%          51.000000
max         166.000000
Name: artist, dtype: float64

In [11]:
# 유저별 play횟수 중앙값에 대한 통계
user_median = data.groupby('user_id')['play'].median()
user_median.describe()

count    358868.000000
mean        142.187676
std         213.089902
min           1.000000
25%          32.000000
50%          83.000000
75%         180.000000
max       50142.000000
Name: play, dtype: float64

In [12]:
# 본인이 좋아하시는 아티스트 데이터로 바꿔서 추가하셔도 됩니다! 단, 이름은 꼭 데이터셋에 있는 것과 동일하게 맞춰주세요.
my_favorite = ['black eyed peas' , 'maroon5' ,'jason mraz' ,'coldplay' ,'beyoncé']

# 'zimin'이라는 user_id가 위 아티스트의 노래를 30회씩 들었다고 가정하겠습니다.
my_playlist = pd.DataFrame({'user_id': ['zimin']*5, 'artist': my_favorite, 'play':[30]*5})

if not data.isin({'user_id':['zimin']})['user_id'].any():  # user_id에 'zimin'이라는 데이터가 없다면
    data = pd.concat([data, my_playlist])                            # 위에 임의로 만든 my_playlist 데이터를 추가해 줍니다.

data.tail(10)       # 잘 추가되었는지 확인해 봅시다.

user_id           artist  play
17535650  sep 20, 2008       turbostaat    12
17535651  sep 20, 2008    cuba missouri    11
17535652  sep 20, 2008  little man tate    11
17535653  sep 20, 2008        sigur rós    10
17535654  sep 20, 2008       the smiths    10
0                zimin  black eyed peas    30
1                zimin          maroon5    30
2                zimin       jason mraz    30
3                zimin         coldplay    30
4                zimin          beyoncé    30

In [13]:
# 고유한 유저, 아티스트를 찾아내는 코드
user_unique = data['user_id'].unique()
artist_unique = data['artist'].unique()

# 유저, 아티스트 indexing 하는 코드 idx는 index의 약자입니다.
user_to_idx = {v:k for k,v in enumerate(user_unique)}
artist_to_idx = {v:k for k,v in enumerate(artist_unique)}

In [14]:
# 인덱싱이 잘 되었는지 확인해 봅니다.
print(user_to_idx['zimin'])    # 358869명의 유저 중 마지막으로 추가된 유저이니 358868이 나와야 합니다.
print(artist_to_idx['black eyed peas'])

358868
376


In [15]:
# indexing을 통해 데이터 컬럼 내 값을 바꾸는 코드
# dictionary 자료형의 get 함수는 https://wikidocs.net/16 을 참고하세요.

# user_to_idx.get을 통해 user_id 컬럼의 모든 값을 인덱싱한 Series를 구해 봅시다.
# 혹시 정상적으로 인덱싱되지 않은 row가 있다면 인덱스가 NaN이 될 테니 dropna()로 제거합니다.
temp_user_data = data['user_id'].map(user_to_idx.get).dropna()
if len(temp_user_data) == len(data):   # 모든 row가 정상적으로 인덱싱되었다면
    print('user_id column indexing OK!!')
    data['user_id'] = temp_user_data   # data['user_id']을 인덱싱된 Series로 교체해 줍니다.
else:
    print('user_id column indexing Fail!!')

# artist_to_idx을 통해 artist 컬럼도 동일한 방식으로 인덱싱해 줍니다.
temp_artist_data = data['artist'].map(artist_to_idx.get).dropna()
if len(temp_artist_data) == len(data):
    print('artist column indexing OK!!')
    data['artist'] = temp_artist_data
else:
    print('artist column indexing Fail!!')

data

user_id column indexing OK!!
artist column indexing OK!!


user_id  artist  play
0         0       0  2137
1         0       1  1099
2         0       2   897
3         0       3   717
4         0       4   706
..      ...     ...   ...
0    358868     376    30
1    358868  270115    30
2    358868    3746    30
3    358868      62    30
4    358868     396    30

[17535660 rows x 3 columns]

In [17]:
# 1회만 play한 데이터의 비율을 보는 코드
only_one = data[data['play']==1]
one, all_data = len(only_one), len(data)
print(f'{one},{all_data}')
print(f'Ratio of only_one over all data is {one/all_data:.2%}')  # f-format에 대한 설명은 https://bit.ly/2DTLqYU

147739,17535660
Ratio of only_one over all data is 0.84%


In [16]:
# 실습 위에 설명보고 이해해서 만들어보기
from scipy.sparse import csr_matrix

num_user = data['user_id'].nunique()
num_artist = data['artist'].nunique()

csr_data = csr_matrix((data.play, (data.user_id, data.artist)), shape= (num_user, num_artist))
csr_data

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 17535578 stored elements and shape (358869, 291347)>

In [18]:
csr_data.shape

(358869, 291347)

## implicit 설치를 해줍니다

In [19]:
!pip install implicit

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.9/8.9 MB 60.7 MB/s eta 0:00:00


In [20]:
from implicit.als import AlternatingLeastSquares
import os
import numpy as np

# implicit 라이브러리에서 권장하고 있는 부분입니다. 학습 내용과는 무관합니다.
os.environ['OPENBLAS_NUM_THREADS']='1'
os.environ['KMP_DUPLICATE_LIB_OK']='True'
os.environ['MKL_NUM_THREADS']='1'

In [21]:
# Implicit AlternatingLeastSquares 모델의 선언
als_model = AlternatingLeastSquares(factors=100, regularization=0.01, use_gpu=False, iterations=15, dtype=np.float32)

/usr/local/lib/python3.11/dist-packages/implicit/cpu/als.py:95: RuntimeWarning: OpenBLAS is configured to use 2 threads. It is highly recommended to disable its internal threadpool by setting the environment variable 'OPENBLAS_NUM_THREADS=1' or by calling 'threadpoolctl.threadpool_limits(1, "blas")'. Having OpenBLAS use a threadpool can lead to severe performance issues here.
  check_blas_config()


# 최신버전으로오면서

item X user 꼴의 matrix 를 받는게 아니라

반대로 바뀌었나봅니다

In [ ]:
# als 모델은 input으로 (item X user 꼴의 matrix를 받기 때문에 Transpose해줍니다.)
# csr_data_transpose = csr_data.T
# csr_data_transpose

In [22]:
# 모델 훈련
als_model.fit(csr_data)

  0%|          | 0/15 [00:00<?, ?it/s]

In [23]:
print("user_factors shape:", als_model.user_factors.shape)
print("item_factors shape:", als_model.item_factors.shape)

user_factors shape: (358869, 100)
item_factors shape: (291347, 100)


In [24]:
zimin, black_eyed_peas = user_to_idx['zimin'], artist_to_idx['black eyed peas']
zimin_vector, black_eyed_peas_vector = als_model.user_factors[zimin], als_model.item_factors[black_eyed_peas]

print('슝=3')

슝=3


In [25]:
zimin_vector

array([-0.6549336 , -0.8739144 , -0.8355626 , -0.6499536 ,  0.6753785 ,
        0.3199908 , -0.07690402,  0.7580761 , -0.5800829 ,  0.449041  ,
        0.80188376,  1.4173993 , -0.8105028 ,  0.17684552,  0.1321551 ,
       -0.62132645, -1.0816803 ,  0.7730293 ,  0.06883481, -0.25338912,
        0.6561864 , -0.1090782 ,  1.7313474 , -0.22963579,  0.0417732 ,
       -0.18580475, -0.1929795 , -0.01274238, -0.98422533, -0.36713395,
        0.5320435 ,  1.412146  ,  0.10914158,  1.3886751 , -0.09732418,
       -0.4361722 , -0.39146182, -0.25831947, -0.5042539 , -0.94500446,
       -0.08965536,  0.60101527, -0.5103989 , -0.95193005,  0.66124165,
        2.0198615 , -0.3201245 , -0.70326877,  0.29313603,  0.55294377,
        0.44479924,  0.71642804, -0.17159228,  0.63586557,  0.648863  ,
        0.5381595 , -1.1619465 ,  0.6352183 ,  0.24278812, -0.6245916 ,
        0.29496807, -0.0023055 , -0.43965614,  0.10215416,  0.45088264,
       -0.4929409 , -0.96496034, -0.1263297 ,  0.05462613, -1.10

In [26]:
black_eyed_peas_vector

array([ 6.5952545e-04,  5.0594392e-03,  1.4206322e-02, -1.3210118e-02,
        2.2547645e-02,  1.4169895e-02, -3.4791152e-03,  1.9270396e-02,
       -4.3173288e-03,  5.6837127e-03,  8.4634209e-03,  1.5228493e-02,
       -8.6047174e-03,  6.4134342e-03,  2.1158628e-02,  5.5636345e-05,
        4.7979783e-03,  2.0496398e-02,  1.8277097e-02,  5.7436046e-03,
        2.3733964e-02,  1.6977249e-02,  8.3431127e-03,  2.2328896e-03,
        1.2408561e-02,  4.6236357e-03,  4.8377784e-03,  6.2747849e-03,
       -3.6246837e-03, -9.7152907e-03,  2.5350692e-02,  2.0179326e-02,
        3.4143599e-03,  3.0442957e-02,  7.8948634e-03, -9.0017971e-03,
        1.7306008e-03, -9.7586690e-03,  4.9252273e-03,  4.2606393e-04,
        8.3131297e-03,  2.1447672e-02,  1.4498003e-02, -1.3461679e-02,
        6.1948178e-03,  1.9633591e-02, -2.9607810e-04, -4.2788191e-03,
       -2.0115010e-03,  8.7324576e-03,  8.4300833e-03,  9.2165973e-03,
        3.1723578e-03,  2.7007803e-02,  1.1952934e-02,  1.0257504e-02,
      

In [27]:
# zimin과 black_eyed_peas를 내적하는 코드
np.dot(zimin_vector, black_eyed_peas_vector)

np.float32(0.50131744)

In [28]:
queen = artist_to_idx['queen']
queen_vector = als_model.item_factors[queen]
np.dot(zimin_vector, queen_vector)

np.float32(0.31303722)

In [29]:
favorite_artist = 'coldplay'
artist_id = artist_to_idx[favorite_artist]
similar_artist = als_model.similar_items(artist_id, N=15)
similar_artist

(array([  62,  277,   28,    5,  217,  473,  247,  490,  268,  910,  418,
         782, 1018,  694,  531], dtype=int32),
 array([0.99999994, 0.9862407 , 0.9739998 , 0.9736565 , 0.97303796,
        0.96785253, 0.9678445 , 0.96182394, 0.95539594, 0.95293206,
        0.95010334, 0.94602066, 0.9434929 , 0.94325703, 0.94147927],
       dtype=float32))

In [32]:
#artist_to_idx 를 뒤집어, index로부터 artist 이름을 얻는 dict를 생성합니다.
idx_to_artist = {v:k for k,v in artist_to_idx.items()}
# [idx_to_artist[i[0]] for i in similar_artist]
[idx_to_artist[i] for i in similar_artist[0]]


['coldplay',
 'muse',
 'the killers',
 'red hot chili peppers',
 'radiohead',
 'placebo',
 'the beatles',
 'oasis',
 'pink floyd',
 'nirvana',
 'u2',
 'the white stripes',
 'the smashing pumpkins',
 'foo fighters',
 'depeche mode']

In [33]:
def get_similar_artist(artist_name: str):
    artist_id = artist_to_idx[artist_name]
    similar_artist = als_model.similar_items(artist_id)
    similar_artist = [idx_to_artist[i] for i in similar_artist[0]]
    return similar_artist

print("슝=3")

슝=3


In [34]:
get_similar_artist('2pac')

['2pac',
 'dr. dre',
 'the game',
 'notorious b.i.g.',
 'snoop dogg',
 '50 cent',
 'ludacris',
 'jay-z',
 'nas',
 'ice cube']

In [35]:
get_similar_artist('lady gaga')

['lady gaga',
 'britney spears',
 'katy perry',
 'rihanna',
 'beyoncé',
 'the pussycat dolls',
 'kelly clarkson',
 'pink',
 'christina aguilera',
 'justin timberlake']

# 오류
filter_already_liked_items=True
로 두면 뭔가 오류가난다

노드에서도 이 부분이 제대로 작동을 안한다고 하는데
최신버전에서도 다른 오류가있는것으로 보임


In [36]:
user = user_to_idx['zimin']
# recommend에서는 user*item CSR Matrix를 받습니다.

# artist_recommended = als_model.recommend(user, csr_data, N=20, filter_already_liked_items=True)
artist_recommended = als_model.recommend(user, csr_data, N=20, filter_already_liked_items=False)
artist_recommended

(array([ 376, 3746,  350,  369,  550,  396,  627, 1800,  354,  409,  274,
         391, 2249,  355,  901,  382,   62,  564, 2902,  621], dtype=int32),
 array([0.50131744, 0.45960516, 0.45832902, 0.45654443, 0.4455226 ,
        0.4402468 , 0.4331736 , 0.41341692, 0.4094645 , 0.40728325,
        0.39315748, 0.38895452, 0.38803273, 0.3854056 , 0.3828158 ,
        0.3765033 , 0.36752918, 0.36351472, 0.36094025, 0.36062992],
       dtype=float32))

In [37]:
[idx_to_artist[i] for i in artist_recommended[0]]

['black eyed peas',
 'jason mraz',
 'rihanna',
 'justin timberlake',
 'britney spears',
 'beyoncé',
 'maroon 5',
 'lady gaga',
 'nelly furtado',
 'amy winehouse',
 'michael jackson',
 'christina aguilera',
 'katy perry',
 'madonna',
 'pink',
 'mika',
 'coldplay',
 'kanye west',
 'james blunt',
 'alicia keys']

In [38]:
rihanna = artist_to_idx['rihanna']
explain = als_model.explain(user, csr_data, itemid=rihanna)

In [39]:
[(idx_to_artist[i[0]], i[1]) for i in explain[1]]

[('beyoncé', np.float64(0.21854626287495807)),
 ('black eyed peas', np.float64(0.15009356484191735)),
 ('jason mraz', np.float64(0.04983580655917913)),
 ('coldplay', np.float64(0.04203511570366444)),
 ('maroon5', np.float64(0.00018606000884620786))]